- name: Ensure Nginx Ingress Helm Repository exists
  kubernetes.core.helm_repository:
    name: "nginx-stable "
    repo_url: "https://helm.nginx.com/stable"

- name: Ensure CertManager Helm Repository exists
  kubernetes.core.helm_repository:
    name: "jetstack"
    repo_url: "https://charts.jetstack.io"

#- name: Ensure CertManager Hetzner Webhook Repository exists
#  kubernetes.core.helm_repository:
#    name: "cert-manager-webhook-hetzner"
#    repo_url: "https://vadimkim.github.io/cert-manager-webhook-hetzner"

- name: Ensure public ingress controller is installed
  kubernetes.core.helm:
    name: ingress-public
    namespace: ingress-system
    create_namespace: true
    chart_ref: nginx-stable/nginx-ingress
    chart_version: 0.15.2

- name: Ensure cert-manager is installed
  kubernetes.core.helm:
    name: cert-manager
    namespace: cert-manager
    create_namespace: true
    chart_ref: jetstack/cert-manager
    chart_version: v1.10.1
    atomic: true
    values:
      installCRDs: true


#- name: Ensure cert-manager-hetzner-webhook is installed
#  kubernetes.core.helm:
#    name: cert-manager
#    namespace: cert-manager
#    create_namespace: true
#    chart_ref: cert-manager-webhook-hetzner/cert-manager-webhook-hetzner
##    chart_version: v1.10.1
#    atomic: true
#    values:
#      groupName=acme.hetzner.com

