apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: infra
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: metallb
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: ~4.1.13
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb
spec:
  addresses:
    - 10.0.100.0/24
