apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: infra
  project: default
  source:
    chart: metallb
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: ~4.1.13
    helm:
      values: |
        configInline:
          address-pools:
          - name: default
            protocol: layer2
            addresses:
            - 10.0.204.0/22
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
