apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-cert2
  namespace: cert-manager
spec:
  commonName: kuard2.dani.rip
  dnsNames:
    - kuard2.dani.rip
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  secretName: example-cert2
