apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-com
  namespace: default
spec:
  secretName: example-com-tls
  commonName: test.dani.rip
  dnsNames:
    - test.dani.rip
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
