apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: 10.0.69.1
      user: ubuntu
      port: 22
      keyPath: ~/.ssh/id_ed25519
    role: controller+worker
  - ssh:
      address: 10.0.42.1
      user: ubuntu
      port: 22
      keyPath: ~/.ssh/id_ed25519
    role: worker
  k0s:
    version: 1.25.4+k0s.0
    dynamicConfig: false
