apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: danielrichter@posteo.de
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
#      - http01:
#          ingress:
#            class: nginx
      - dns01:
          webhook:
            groupName: acme.dani.rip
            solverName: hetzner
            config:
              secretName: hetzner-secret
              apiUrl: https://dns.hetzner.com/api/v1
