- name: Ensure ingress-nginx Helm Repo exists
  kubernetes.core.helm_repository:
    name: ingress-nginx
    repo_url: https://kubernetes.github.io/ingress-nginx

- name: Ensure certmanager Helm Repo exists
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

- name: Ensure ingress-public is installed
  kubernetes.core.helm:
    name: ingress-public
    namespace: ingress-system
    create_namespace: true
    chart_ref: ingress-nginx/ingress-nginx
    chart_version: 4.4.2

- name: Ensure cert-manager is installed
  kubernetes.core.helm:
    name: cert-manager
    namespace: cert-manager
    create_namespace: true
    chart_ref: jetstack/cert-manager
    chart_version: v1.10.1
    atomic: true
    values:
      installCRDs: true

