apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
  finalizers:
    - resources-finalizer.99_argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  addresses:
    - 10.0.200.1-10.0.200.254
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2a
  namespace: metallb-system
