apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: 99_argocd
  finalizers:
    - resources-finalizer.99_argocd.argoproj.io
spec:
  destination:
    namespace: metallb-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: metallb
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: ~4.1.13
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
