apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrap
  namespace: 999_argocd
  finalizers:
  - resources-finalizer.999_argocd.argoproj.io
spec:
  destination:
    namespace: 999_argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: bootstrap
    repoURL: https://github.com/danielr1996/k8s-gitops.git
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated: {}
