apiVersion: v1
kind: ConfigMap
metadata:
  name: 999_argocd-cmd-params-cm
  namespace: 999_argocd
  labels:
    app.kubernetes.io/name: 999_argocd-cmd-params-cm
    app.kubernetes.io/part-of: 999_argocd
data:
  server.insecure: "true"
