packages:
  - apt_key:
      id: "2472D6D0D2F66AF87ABA8DA34D64390375060AA4"
      url: "https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:1.25/xUbuntu_22.04/Release.key"
    apt_repository: "deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.25/xUbuntu_22.04/ /"
    packages:
      - cri-o
  - apt_key:
      id: "2472D6D0D2F66AF87ABA8DA34D64390375060AA4"
      url: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04/Release.key"
    apt_repository: "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04/ /"
    packages:
      - cri-o-runc
  - apt_key:
      id: "A362B822F6DEDC652817EA46B53DC80D13EDEF05"
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    apt_repository: "deb http://packages.cloud.google.com/apt/ kubernetes-xenial main"
    packages:
      - kubelet
      - kubeadm
      - kubectl
holdpackages:
  - kubelet
  - kubeadm
  - kubectl
