---
- hosts: localhost
  pre_tasks:
    - name: "ensure helm repository key is present"
      become: yes
      ansible.builtin.apt_key:
        id: 81BF832E2F19CD2AA0471959294AC4827C1A168A
        url: https://baltocdn.com/helm/signing.asc
        state: present
    - name: "ensure kubectl repository key is present"
      become: yes
      ansible.builtin.apt_key:
        id: "A362B822F6DEDC652817EA46B53DC80D13EDEF05"
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present
    - name: "ensure helm repository is present"
      become: yes
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://baltocdn.com/helm/stable/debian/ all main"
        state: present
    - name: "ensure kubectl repository is present"
      become: yes
      ansible.builtin.apt_repository:
        repo: "deb http://packages.cloud.google.com/apt/ kubernetes-xenial main"
        state: present
    - name: "ensure helm package is installed"
      become: yes
      apt:
        name: helm
        state: present
    - name: "ensure kubectl package is installed"
      become: yes
      apt:
        name: kubectl
        state: present
    - name: Ensure openshift python package exists
      pip:
        name:
          - openshift
- hosts: localhost
  roles:
#    - name: provision-metallb
#      tags: [never, metallb]
#    - name: provision-ingress
#      tags: [never, ingress]
    - name: reset-storage-localhost
      tags: [never, storage]
- hosts: worker
  roles:
    - name: reset-storage-worker
      tags: [never, storage]
