---
- hosts: 127.0.0.1
  pre_tasks:
    - name: convert ssh_key from CRLF to LF line endings
      template:
        src: ./ssh_key_terraform
        dest: ./ssh_key
        mode: 0600
    - name: "ensure helm repository key is present"
      become: yes
      ansible.builtin.apt_key:
        id: 81BF832E2F19CD2AA0471959294AC4827C1A168A
        url: https://baltocdn.com/helm/signing.asc
        state: present
    - name: "ensure kubectl repository key is present"
      become: yes
      ansible.builtin.apt_key:
        id: "A362B822F6DEDC652817EA46B53DC80D13EDEF05"
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present
    - name: "ensure helm repository is present"
      become: yes
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://baltocdn.com/helm/stable/debian/ all main"
        state: present
    - name: "ensure kubectl repository is present"
      become: yes
      ansible.builtin.apt_repository:
        repo: "deb http://packages.cloud.google.com/apt/ kubernetes-xenial main"
        state: present
    - name: "ensure helm package is installed"
      become: yes
      apt:
        name: helm
        state: present
    - name: "ensure kubectl package is installed"
      become: yes
      apt:
        name: kubectl
        state: present
    - name: Ensure openshift python package exists
      pip:
        name:
          - openshift
# Configuration and Installation
- hosts: all
  roles:
    - role: prepare-machineid
      tags:
        - config
    - role: 1_installation
      tags:
        - never
        - installation

# Loadbalancer
- hosts: controlplane
  roles:
    - role: prepare-loadbalancer
      tags:
        - never
        - loadbalancer
# Kubeadm init
- hosts: controlplane-first
  roles:
    - role: 3_kubeadm-init
      tags:
        - never
        - kubeadm
        - kubeadm-init

# Kubeadm join controlplane
- hosts: controlplane-rest
  roles:
    - role: 4_kubeadm-join-master
      tags:
        - never
        - kubeadm
        - kubeadm-join

# Kubeadm join worker
- hosts: worker
  roles:
    - role: 6_kubeadm-join-worker
      tags:
        - never
        - kubeadm
        - kubeadm-join
# Bootstrap additional addons like cni, provision-storage, loadbalancer, etc.
- hosts: localhost
  roles:
    - role: 7_bootstrap
      tags:
        - never
        - bootstrap
# Configure provision-ingress
- hosts: localhost
  roles:
    - role: 8_ingress
      tags:
        - never
        - provision-ingress
- hosts: all
  roles:
    - role: 99_reset
      tags:
        - reset
        - never
