- name: Ensure Bitnami Helm Repo
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: https://charts.bitnami.com/bitnami

- name: Ensure metallb is installed
  kubernetes.core.helm:
    name: argocd
    namespace: argocd-system
    create_namespace: true
    chart_ref: bitnami/argo-cd
    chart_version: 4.4.0

#- name: Ensure IPAddressPool is installed
#  kubernetes.core.k8s:
#    state: present
#    definition:
#      apiVersion: metallb.io/v1beta1
#      kind: IPAddressPool
#      metadata:
#        name: default-ipaddresspool
#        namespace: metallb-system
#      spec:
#        addresses:
#          - 10.0.204.1-10.0.204.254
#
#- name: Ensure L2Advertisement is installed
#  kubernetes.core.k8s:
#    state: present
#    definition:
#      apiVersion: metallb.io/v1beta1
#      kind: L2Advertisement
#      metadata:
#        name: default-l2advertisement
#        namespace: metallb-system
#
